name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
        go:
          - "stable"
          - "1.22"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: |
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"
        shell: bash
      - run: make depend
      - run: make test
