name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
        go:
          - "stable"
          - "1.22"
          - "1.21"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - run: make test

      - name: upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./profile.cov
          flags: ${{ matrix.go }}
          token: ${{ secrets.CODECOV_TOKEN }}
