name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
        go:
          - "stable"
          - "1.23"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          path: src/github.com/shogo82148/shogoa
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: |
          go version
          echo "GO111MODULE=on" >> "$GITHUB_ENV"
          echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"
        shell: bash
      - run: make depend
        working-directory: src/github.com/shogo82148/shogoa
      - run: make test
        working-directory: src/github.com/shogo82148/shogoa
      - name: upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: src/github.com/shogo82148/shogoa/coverage.txt
          flags: ${{ matrix.os }}-${{ matrix.go }}
